# Generated by Django 2.2.7 on 2020-06-02 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasource',
            old_name='schema',
            new_name='stream',
        ),
    ]
