# Generated by Django 2.2.7 on 2020-06-02 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0010_stream_schema'),
        ('integration', '0003_remove_datasource_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='stream',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='streams.Stream'),
            preserve_default=False,
        ),
    ]
