# Generated by Django 2.2.7 on 2020-06-10 16:57

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20200609_1111'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integration', '0004_datasource_stream'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='Table Data')),
                ('headers', django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='Table Headers')),
                ('file', models.FileField(null=True, upload_to='files', verbose_name='JSON/CSV File')),
                ('content_type', models.CharField(max_length=100, null=True, verbose_name='Content Type')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Table Data Count')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Import Data',
                'verbose_name_plural': 'Import Data',
                'ordering': ('id',),
            },
        ),
    ]
