# Generated by Django 2.2.7 on 2020-06-12 13:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0005_importdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='importdata',
            name='stream_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='Map Data To Definition Fields'),
        ),
        migrations.AddField(
            model_name='importdata',
            name='use_schema',
            field=models.CharField(choices=[('new', 'New Event Definition'), ('existing', 'Existing Event Definition')], default='new', max_length=100, verbose_name='Destination Of New Or Existing Definition'),
        ),
    ]
