# Generated by Django 2.2.7 on 2019-12-24 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_developer_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='developer_key',
        ),
    ]
