# Generated by Django 2.2.7 on 2020-01-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('developer', 'Data Developer'), ('user', 'Data User')], default='developer', max_length=9, verbose_name='Type'),
        ),
    ]
