# Generated by Django 2.2.7 on 2020-06-09 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200608_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='default_CLUSTER_ENDPOINT',
            new_name='default_cluster_endpoint',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='default_CLUSTER_TYPE',
            new_name='default_cluster_type',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='default_DRUID_URL',
            new_name='default_druid_url',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='default_KAFKA_URL',
            new_name='default_kafka_url',
        ),
    ]
