# Generated by Django 2.2.7 on 2020-06-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20200609_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='kafka_url_public',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='default_cluster_endpoint',
            field=models.CharField(blank=True, default='N/A', max_length=256, null=True),
        ),
    ]
