# Generated by Django 2.2.7 on 2020-01-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datadictionaries', '0003_dataitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataitem',
            name='source_value',
            field=models.CharField(max_length=64, unique=True, verbose_name='Source value'),
        ),
    ]
