# Generated by Django 2.2.7 on 2019-12-16 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('db_type', models.CharField(choices=[('druid', 'Druid')], max_length=200, verbose_name='Type')),
                ('server', models.CharField(max_length=500, verbose_name='Server')),
                ('port', models.CharField(max_length=20, verbose_name='Port')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'verbose_name': 'Database',
                'verbose_name_plural': 'Databases',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('broker_type', models.CharField(choices=[('kafka', 'Kafka')], max_length=200, verbose_name='Type')),
                ('url', models.CharField(max_length=500, verbose_name='Url')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'verbose_name': 'Broker',
                'verbose_name_plural': 'Brokers',
                'ordering': ('id',),
            },
        ),
    ]
