# Generated by Django 2.2.7 on 2019-12-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_broker_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Is Default Broker?'),
        ),
        migrations.AddField(
            model_name='database',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Is Default Database?'),
        ),
    ]
