# Generated by Django 2.2.7 on 2019-12-24 11:59

from django.db import migrations, models
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20191217_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='developer_key',
            field=models.CharField(default=secrets.token_hex, max_length=64, verbose_name='developer key'),
        ),
    ]
