# Generated by Django 2.2.7 on 2020-01-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_developer_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=400, null=True, verbose_name='Description'),
        ),
    ]
