# Generated by Django 2.2.7 on 2020-06-08 14:14

from django.db import migrations, models
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20200117_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_key',
            field=models.CharField(default=secrets.token_hex, max_length=64, verbose_name='project_key'),
        ),
    ]
