# Generated by Django 2.2.7 on 2020-06-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_project_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='default_cluster_endpoint',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='default_cluster_type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='default_druid_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='default_kafka_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
