# Generated by Django 2.2.7 on 2020-06-01 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0002_auto_20200601_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchitem',
            name='search',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='searches.Search'),
            preserve_default=False,
        ),
    ]
