# Generated by Django 2.2.7 on 2020-06-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0003_searchitem_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchitem',
            name='search_field',
            field=models.CharField(default='', max_length=200, verbose_name='Search Field'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchitem',
            name='search_value',
            field=models.CharField(default='', max_length=200, verbose_name='Search Value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchitem',
            name='time_window',
            field=models.CharField(default='1 hour', max_length=200, verbose_name='Time Window'),
        ),
        migrations.AlterField(
            model_name='searchitem',
            name='stream',
            field=models.CharField(max_length=200, null=True, verbose_name='Stream'),
        ),
    ]
