# Generated by Django 2.2.7 on 2020-06-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0005_auto_20200602_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='search_field',
            field=models.CharField(blank=True, max_length=200, verbose_name='Search Field'),
        ),
        migrations.AlterField(
            model_name='search',
            name='search_value',
            field=models.CharField(blank=True, max_length=200, verbose_name='Search Value'),
        ),
        migrations.AlterField(
            model_name='search',
            name='stream',
            field=models.CharField(default='', max_length=200, verbose_name='Stream'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='search',
            name='time_window',
            field=models.CharField(blank=True, default='1 hour', max_length=200, verbose_name='Time Window'),
        ),
    ]
