# Generated by Django 2.2.7 on 2020-06-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0006_auto_20200602_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='search_field',
        ),
        migrations.RemoveField(
            model_name='search',
            name='search_value',
        ),
        migrations.AddField(
            model_name='search',
            name='search_data',
            field=models.TextField(blank=True, verbose_name='Search Data'),
        ),
    ]
