# Generated by Django 2.2.7 on 2019-11-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamprocessors', '0003_auto_20191118_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamprocessor',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='streamprocessor',
            name='dsl',
            field=models.TextField(blank=True, null=True),
        ),
    ]
