# Generated by Django 2.2.7 on 2019-11-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamprocessors', '0004_auto_20191118_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('broker', models.TextField(blank=True, null=True)),
                ('consumer', models.IntegerField(default=0)),
            ],
        ),
    ]
