# Generated by Django 2.2.7 on 2019-11-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamprocessors', '0006_streamprocessorstep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streamprocessorstep',
            old_name='type',
            new_name='steptype',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='consumer',
        ),
        migrations.AddField(
            model_name='stream',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='broker',
            field=models.CharField(default='StatelessFilter', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='streamprocessorstep',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
    ]
