# Generated by Django 2.2.7 on 2019-11-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamprocessors', '0007_auto_20191128_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='streamprocessorstep',
            name='description',
            field=models.TextField(blank=True, default='Description'),
            preserve_default=False,
        ),
    ]
