# Generated by Django 2.2.7 on 2019-11-30 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamprocessors', '0009_auto_20191129_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='streamprocessor',
            options={'ordering': ('id',), 'verbose_name': 'StreamProcessor', 'verbose_name_plural': 'StreamProcessors'},
        ),
    ]
