# Generated by Django 2.2.7 on 2019-11-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamprocessors', '0010_auto_20191130_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamprocessorstep',
            name='ordering',
            field=models.IntegerField(default=1, verbose_name='Ordering steps'),
        ),
    ]
