# Generated by Django 2.2.7 on 2019-12-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamprocessors', '0012_auto_20191202_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamprocessorstep',
            name='destination',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Destination'),
        ),
        migrations.AddField(
            model_name='streamprocessorstep',
            name='source',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Source'),
        ),
    ]
