# Generated by Django 2.2.7 on 2019-12-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamprocessors', '0013_auto_20191203_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamprocessorstep',
            name='steptype',
            field=models.CharField(choices=[('inbound', 'Inbound Event'), ('outbound', 'Outbound Event'), ('filter', 'Simple Filter'), ('map', 'Map'), ('lookup', 'Record Lookup'), ('key', 'Record Key Performance Indicator')], max_length=8, verbose_name='Type'),
        ),
    ]
