# Generated by Django 2.2.7 on 2019-12-16 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamprocessors', '0016_streamprocessorstep_database'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamprocessorstep',
            name='broker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Broker'),
        ),
    ]
