# Generated by Django 2.2.7 on 2019-12-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamprocessors', '0017_auto_20191216_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamprocessor',
            name='replicas',
            field=models.PositiveIntegerField(default=1, verbose_name='Count Of Replicas'),
        ),
    ]
