# Generated by Django 2.2.7 on 2020-01-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamprocessors', '0018_streamprocessor_replicas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamprocessorstep',
            name='broker',
        ),
        migrations.RemoveField(
            model_name='streamprocessorstep',
            name='database',
        ),
    ]
