# Generated by Django 2.2.7 on 2020-01-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamprocessors', '0020_auto_20200108_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamprocessorstep',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Recipient Email Address'),
        ),
        migrations.AddField(
            model_name='streamprocessorstep',
            name='field_to_process',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Field To Process'),
        ),
        migrations.AddField(
            model_name='streamprocessorstep',
            name='file_path',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='File Path'),
        ),
        migrations.AddField(
            model_name='streamprocessorstep',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telephone Number'),
        ),
        migrations.AddField(
            model_name='streamprocessorstep',
            name='template',
            field=models.TextField(blank=True, null=True, verbose_name='SMS/Email template'),
        ),
        migrations.AlterField(
            model_name='streamprocessorstep',
            name='steptype',
            field=models.CharField(choices=[('inbound', 'Inbound Event - Stream'), ('outbound', 'Outbound Event - Stream'), ('outboundemal', 'Outbound Event - E-Mail'), ('outboundsms', 'Outbound Event - SMS'), ('outboundweb', 'Outbound Event - Web Hook'), ('filter', 'Processor - Simple Filter'), ('map', 'Processor - Map Function'), ('lookup', 'Processor - Record Lookup'), ('key', 'Processor - Record Key Performance Indicator'), ('workflow', 'Processor - Create Workflow Task'), ('sentiment', 'Processor - AWS Comprehend Sentiment Analysis'), ('transcribe', 'Processor - AWS Transcribe Task')], max_length=8, verbose_name='Type'),
        ),
    ]
