# Generated by Django 2.2.7 on 2020-01-14 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streamprocessors', '0020_auto_20200108_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('streamprocessor_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='streamprocessors.StreamProcessorStep')),
            ],
            options={
                'verbose_name': 'WorkflowTask',
                'verbose_name_plural': 'WorkflowTasks',
                'ordering': ('id',),
            },
        ),
    ]
