# Generated by Django 2.2.7 on 2020-01-14 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamprocessors', '0021_auto_20200114_1008'),
        ('streamprocessors', '0022_auto_20200114_0907'),
    ]

    operations = [
    ]
