# Generated by Django 2.2.7 on 2020-01-15 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamprocessors', '0025_auto_20200115_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streamprocessorstep',
            old_name='stream',
            new_name='lookup_stream',
        ),
    ]
