# Generated by Django 2.2.7 on 2020-01-15 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamprocessors', '0026_auto_20200115_1331'),
        ('streamprocessors', '0025_auto_20200115_1234'),
    ]

    operations = [
    ]
