# Generated by Django 2.2.7 on 2020-01-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamprocessors', '0027_merge_20200115_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streamprocessorstep',
            old_name='key_value',
            new_name='field_name',
        ),
        migrations.AddField(
            model_name='streamprocessorstep',
            name='static_value',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Static Value'),
        ),
        migrations.AlterField(
            model_name='streamprocessorstep',
            name='steptype',
            field=models.CharField(choices=[('inbound', 'Inbound Event - Stream'), ('outbound', 'Outbound Event - Stream'), ('outboundemail', 'Outbound Event - E-Mail'), ('outboundsms', 'Outbound Event - SMS'), ('outboundweb', 'Outbound Event - Web Hook'), ('filter', 'Processor - Simple Filter'), ('map', 'Processor - Map Function'), ('lookup', 'Processor - Record Lookup'), ('key', 'Processor - Record Key Performance Indicator'), ('workflow', 'Processor - Create Workflow Task'), ('sentiment', 'Processor - AWS Comprehend Sentiment Analysis'), ('transcribe', 'Processor - AWS Transcribe Task')], max_length=100, verbose_name='Type'),
        ),
    ]
