# Generated by Django 2.2.7 on 2020-01-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamprocessors', '0029_auto_20200122_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamprocessorstep',
            name='line_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Value'),
        ),
    ]
