# Generated by Django 2.2.7 on 2020-01-24 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamprocessors', '0031_auto_20200123_1721'),
        ('streamprocessors', '0030_auto_20200123_1431'),
    ]

    operations = [
    ]
