# Generated by Django 2.2.7 on 2020-01-24 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamprocessors', '0032_merge_20200124_0631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamprocessorstep',
            name='time_period',
        ),
    ]
