# Generated by Django 2.2.7 on 2020-01-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamprocessors', '0038_auto_20200129_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamprocessorstep',
            name='code',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='streamprocessorstep',
            name='duration',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='streamprocessorstep',
            name='poll_interval',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Poll interval'),
        ),
        migrations.AddField(
            model_name='streamprocessorstep',
            name='schedule',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Schedule'),
        ),
    ]
