# Generated by Django 2.2.7 on 2020-02-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamprocessors', '0042_streamprocessorstep_timestamp_field_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamprocessor',
            name='additional_integrity_checks',
            field=models.BooleanField(default=False, verbose_name='Additional Integrity Checks'),
        ),
        migrations.AddField(
            model_name='streamprocessor',
            name='delay_on_uuid_failure',
            field=models.PositiveIntegerField(default=0, verbose_name='Delay On uuid Failure'),
        ),
        migrations.AddField(
            model_name='streamprocessor',
            name='retry_on_uuid_failure_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Retry On uuid Failure Count'),
        ),
    ]
