# Generated by Django 2.2.7 on 2020-02-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamprocessors', '0044_auto_20200205_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamprocessorstep',
            name='adjust_field_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Field Name'),
        ),
        migrations.AddField(
            model_name='streamprocessorstep',
            name='field_operation',
            field=models.CharField(blank=True, choices=[('+', 'Add To'), ('-', 'Substract From'), ('*', 'Multiple By')], max_length=100, null=True, verbose_name='Field Operation'),
        ),
        migrations.AddField(
            model_name='streamprocessorstep',
            name='result_placement_numeric',
            field=models.CharField(blank=True, choices=[('select', ' Add To A New Field'), ('replace', ' Replace In Place')], max_length=100, null=True, verbose_name='Result Placement'),
        ),
        migrations.AlterField(
            model_name='streamprocessorstep',
            name='steptype',
            field=models.CharField(choices=[('inbound', 'Inbound Event - Stream'), ('inboundtimer', 'Inbound Event - Timer Task'), ('inboundttp', 'Inbound Event - Load From HTTP Source'), ('outbound', 'Outbound Event - Stream'), ('outboundemail', 'Outbound Event - E-Mail'), ('outboundsms', 'Outbound Event - SMS'), ('outboundweb', 'Outbound Event - Web Hook'), ('filter', 'Processor - Simple Filter'), ('map', 'Processor - Map Function'), ('lookup', 'Processor - Stream Lookup'), ('key', 'Processor - Record Key Performance Indicator'), ('workflow', 'Processor - Create Workflow Task'), ('sentiment', 'Processor - AWS Comprehend Sentiment Analysis'), ('transcribe', 'Processor - AWS Transcribe Task'), ('external', 'Processor - External API Call'), ('manipulate', 'Processor - Manipulate Fields'), ('sleep', 'Processor - Sleep Step'), ('python', 'Processor - Python Step'), ('reset', 'Processor - Reset Timestamp'), ('dict', 'Processor - Data Dictionary Lookup & Replace'), ('adjust', 'Processor - Adjust Numeric Field')], max_length=100, verbose_name='Type'),
        ),
    ]
