# Generated by Django 2.2.7 on 2020-02-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamprocessors', '0046_auto_20200205_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamprocessorstep',
            name='add_field_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Add Field Name'),
        ),
        migrations.AddField(
            model_name='streamprocessorstep',
            name='copy_field_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Copy Field Name'),
        ),
        migrations.AddField(
            model_name='streamprocessorstep',
            name='destination_field_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Destination Field Name'),
        ),
        migrations.AddField(
            model_name='streamprocessorstep',
            name='field_value',
            field=models.CharField(blank=True, max_length=200, verbose_name='Add Field Value'),
        ),
        migrations.AddField(
            model_name='streamprocessorstep',
            name='new_field_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='New Field Name'),
        ),
        migrations.AddField(
            model_name='streamprocessorstep',
            name='remove_field_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Remove Field Name'),
        ),
        migrations.AddField(
            model_name='streamprocessorstep',
            name='rename_field_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Rename Field Name'),
        ),
        migrations.AddField(
            model_name='streamprocessorstep',
            name='sum_fields',
            field=models.CharField(blank=True, max_length=400, verbose_name='Sum Field Names'),
        ),
        migrations.AddField(
            model_name='streamprocessorstep',
            name='target_field_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Target Field Name'),
        ),
        migrations.AlterField(
            model_name='streamprocessorstep',
            name='steptype',
            field=models.CharField(choices=[('inbound', 'Inbound Event - Stream'), ('inboundtimer', 'Inbound Event - Timer Task'), ('inboundttp', 'Inbound Event - Load From HTTP Source'), ('outbound', 'Outbound Event - Stream'), ('outboundemail', 'Outbound Event - E-Mail'), ('outboundsms', 'Outbound Event - SMS'), ('outboundweb', 'Outbound Event - Web Hook'), ('filter', 'Processor - Simple Filter'), ('map', 'Processor - Map Function'), ('lookup', 'Processor - Stream Lookup'), ('key', 'Processor - Record Key Performance Indicator'), ('workflow', 'Processor - Create Workflow Task'), ('sentiment', 'Processor - AWS Comprehend Sentiment Analysis'), ('transcribe', 'Processor - AWS Transcribe Task'), ('external', 'Processor - External API Call'), ('manipulate', 'Processor - Manipulate Fields'), ('add', 'Processor - Add Field'), ('remove', 'Processor - Remove Field'), ('copy', 'Processor - Copy Field'), ('rename', 'Processor - Rename Field'), ('sum', 'Processor - Rename Field'), ('sleep', 'Processor - Sleep Step'), ('python', 'Processor - Python Step'), ('reset', 'Processor - Reset Timestamp'), ('dict', 'Processor - Data Dictionary Lookup & Replace'), ('adjust', 'Processor - Adjust Numeric Field'), ('value', 'Processor - If Value In Set')], max_length=100, verbose_name='Type'),
        ),
    ]
