# Generated by Django 2.2.7 on 2020-02-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamprocessors', '0050_auto_20200206_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamprocessor',
            name='delay_on_uuid_failure',
            field=models.PositiveIntegerField(default=50, verbose_name='Delay On uuid Failure'),
        ),
        migrations.AlterField(
            model_name='streamprocessor',
            name='retry_on_uuid_failure_count',
            field=models.PositiveIntegerField(default=10, verbose_name='Retry On uuid Failure Count'),
        ),
    ]
