# Generated by Django 2.2.7 on 2020-02-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamprocessors', '0051_auto_20200210_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamprocessorstep',
            name='offset',
            field=models.CharField(choices=[('latest', 'Process Events That Occur After Deployment'), ('earliest', 'Process All Historical Events')], default='latest', max_length=200, verbose_name='Offset'),
        ),
    ]
