# Generated by Django 2.2.7 on 2020-03-06 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamprocessors', '0054_auto_20200305_1307'),
        ('streamprocessors', '0053_auto_20200303_0641'),
    ]

    operations = [
    ]
