# Generated by Django 2.2.11 on 2020-03-09 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamprocessors', '0055_merge_20200306_1226'),
        ('streamprocessors', '0056_auto_20200306_1111'),
    ]

    operations = [
    ]
