# Generated by Django 2.2.7 on 2020-03-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamprocessors', '0058_auto_20200311_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamprocessorstep',
            name='schedule_type',
            field=models.CharField(blank=True, choices=[('every_x_minutes', 'Every x minutes'), ('every_day_at', 'Every day at')], max_length=100, null=True, verbose_name='Schedule Type'),
        ),
    ]
