# Generated by Django 2.2.7 on 2020-05-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamprocessors', '0059_streamprocessorstep_schedule_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamprocessorstep',
            name='event_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Schema drop down'),
        ),
        migrations.AlterField(
            model_name='streamprocessorstep',
            name='result_placement',
            field=models.CharField(blank=True, choices=[('aggregate', 'Aggregate Results and Add To Event'), ('aggregateregister', 'Aggregate Results and Register In Variable'), ('join', 'Join Results To Inbound'), ('joininbound', 'Join Inbound To Results'), ('replace', 'Replace Inbound Event With Results')], max_length=20, null=True, verbose_name='Result Placement'),
        ),
        migrations.AlterField(
            model_name='streamprocessorstep',
            name='steptype',
            field=models.CharField(choices=[('inbound', 'Inbound Event - Stream'), ('inboundtimer', 'Inbound Event - Timer Task'), ('inboundttp', 'Inbound Event - Load From API'), ('inboundkpi', 'Inbound Event - KPI Change'), ('outbound', 'Outbound Event - Stream'), ('outboundemail', 'Outbound Event - E-Mail'), ('outboundsms', 'Outbound Event - SMS'), ('outboundweb', 'Outbound Event - Web Hook'), ('function', 'Processor - Execute Function'), ('filter', 'Processor - Simple Filter'), ('select', 'Processor - Select Fields'), ('complex', 'Processor - Complex Filter'), ('map', 'Processor - Map Function'), ('event', 'Processor - Create New Event Of Type'), ('lookup', 'Processor - Stream Lookup'), ('key', 'Processor - Record Key Performance Indicator'), ('workflow', 'Processor - Create Workflow Task'), ('sentiment', 'Processor - AWS Comprehend Sentiment Analysis'), ('transcribe', 'Processor - AWS Transcribe Task'), ('external', 'Processor - External API Call'), ('add', 'Processor - Add Field'), ('remove', 'Processor - Remove Field'), ('copy', 'Processor - Copy Field'), ('rename', 'Processor - Rename Field'), ('sum', 'Processor - Sum Field'), ('sleep', 'Processor - Sleep Step'), ('python', 'Processor - Python Step'), ('reset', 'Processor - Reset Timestamp'), ('dict', 'Processor - Data Dictionary Lookup & Replace'), ('adjust', 'Processor - Perform Calculation'), ('value', 'Processor - If Value In Set')], max_length=100, verbose_name='Type'),
        ),
    ]
