# Generated by Django 2.2.7 on 2020-05-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamprocessors', '0064_auto_20200507_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamprocessorstep',
            name='destinations',
            field=models.CharField(blank=True, max_length=100, verbose_name='Destinations'),
        ),
    ]
