# Generated by Django 2.2.7 on 2020-05-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamprocessors', '0066_auto_20200507_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamprocessorstep',
            name='variable_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Variable Name'),
        ),
    ]
