# Generated by Django 2.2.7 on 2020-05-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamprocessors', '0069_auto_20200511_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamprocessorstep',
            name='event_field_name_new',
            field=models.CharField(blank=True, max_length=100, verbose_name='Event Field Name'),
        ),
        migrations.AddField(
            model_name='streamprocessorstep',
            name='key_type_new',
            field=models.CharField(blank=True, choices=[('from_event', 'A Value From Event'), ('static_value', 'A Static Value')], max_length=20, null=True, verbose_name='Key Type'),
        ),
        migrations.AddField(
            model_name='streamprocessorstep',
            name='static_value_new',
            field=models.CharField(blank=True, max_length=100, verbose_name='Static Value'),
        ),
        migrations.AddField(
            model_name='streamprocessorstep',
            name='variable_name_new',
            field=models.CharField(blank=True, max_length=100, verbose_name='Variable Name'),
        ),
    ]
