# Generated by Django 2.2.7 on 2020-05-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamprocessors', '0072_streamprocessorstep_variable_name_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamprocessorstep',
            name='key_type',
            field=models.CharField(blank=True, choices=[('from_event', 'A Value From Event'), ('static_value', 'A Static Value')], max_length=40, null=True, verbose_name='Key Type'),
        ),
    ]
