# Generated by Django 2.2.7 on 2020-06-16 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamprocessors', '0075_auto_20200612_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamprocessorstep',
            name='streamprocessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='streamprocessors.StreamProcessor'),
        ),
    ]
