# Generated by Django 2.2.7 on 2020-07-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamprocessors', '0078_auto_20200703_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamprocessorstep',
            name='key_type',
            field=models.CharField(blank=True, choices=[('from_event', 'A Value From Event'), ('static_value', 'A Static Value'), ('from_variable', 'A Value From A Registered Variable')], max_length=40, null=True, verbose_name='Key Type'),
        ),
        migrations.AlterField(
            model_name='streamprocessorstep',
            name='key_type_from',
            field=models.CharField(blank=True, choices=[('from_event', 'A Value From Event'), ('static_value', 'A Static Value'), ('from_variable', 'A Value From A Registered Variable')], max_length=20, null=True, verbose_name='Key Type'),
        ),
    ]
