# Generated by Django 2.2.7 on 2020-07-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamprocessors', '0080_streamprocessorstep_field_to_replace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamprocessorstep',
            name='key_type',
            field=models.CharField(blank=True, choices=[('from_event', 'A Value From Event'), ('static_value', 'A Static Value'), ('from_variable', 'A Value From A Registered Variable'), ('one', 'Increment By One'), ('from_event', 'Increment By A Value From The Event'), ('static_value', 'Increment By A Static Value'), ('update_from_event', 'Update To Value From event'), ('update_to_static_value', 'Update To Static Value'), ('update_to_registered_variable', 'Update To Registered Variable')], max_length=40, null=True, verbose_name='Key Type'),
        ),
    ]
