# Generated by Django 2.2.7 on 2020-08-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamprocessors', '0081_auto_20200715_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamprocessorstep',
            name='schedule_value',
            field=models.IntegerField(blank=True, default=0, verbose_name='Schedule Type'),
        ),
        migrations.AlterField(
            model_name='streamprocessorstep',
            name='schedule_type',
            field=models.CharField(blank=True, choices=[('every_x_millisecond', 'Every x milliseconds'), ('every_x_second', 'Every x seconds'), ('every_x_minutes', 'Every x minutes'), ('every_x_hour', 'Every x hours'), ('every_x_day', 'Every x days'), ('every_day_at', 'Every day at')], max_length=100, null=True, verbose_name='Schedule Type'),
        ),
    ]
