# Generated by Django 2.2.7 on 2020-08-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamprocessors', '0083_auto_20200804_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamprocessorstep',
            name='schedule_value',
            field=models.IntegerField(default=0, verbose_name='Schedule Value'),
        ),
    ]
