# Generated by Django 2.2.7 on 2019-12-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20191202_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='dsl',
            field=models.TextField(blank=True, null=True, verbose_name='Dsl'),
        ),
    ]
