# Generated by Django 2.2.7 on 2019-12-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_report_dsl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportitem',
            name='type',
            field=models.TextField(blank=True, choices=[('data_table', 'data_table'), ('bar_chart', 'bar-chart'), ('line_chart', 'line-chart'), ('summary', 'summary')], null=True, verbose_name='Type'),
        ),
    ]
