# Generated by Django 2.2.7 on 2019-12-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_auto_20191209_0741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportitem',
            name='filter',
        ),
        migrations.AddField(
            model_name='reportitem',
            name='filter_field',
            field=models.TextField(blank=True, null=True, verbose_name='Filter Field'),
        ),
        migrations.AddField(
            model_name='reportitem',
            name='filter_value',
            field=models.TextField(blank=True, null=True, verbose_name='Filter Value'),
        ),
    ]
