# Generated by Django 2.2.7 on 2020-02-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_report_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportitem',
            name='filter_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Less Than'), (1, 'Greater Than'), (2, 'Equal')], null=True, verbose_name='Filter type'),
        ),
        migrations.AddField(
            model_name='reportitem',
            name='ordering',
            field=models.IntegerField(default=1, verbose_name='Ordering records'),
        ),
        migrations.AddField(
            model_name='reportitem',
            name='time_window',
            field=models.IntegerField(blank=True, choices=[(0, 'Last Minute'), (1, 'Last 10 Minutes'), (2, 'Last Hour'), (3, 'Last Day'), (4, 'Last Week'), (5, 'Last Year')], null=True, verbose_name='Time window'),
        ),
    ]
