# Generated by Django 2.2.7 on 2020-02-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_auto_20200210_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportitem',
            name='filter_type',
            field=models.IntegerField(blank=True, choices=[('less_than', 'Less Than'), ('greater_than', 'Greater Than'), ('equal', 'Equal')], max_length=20, null=True, verbose_name='Filter type'),
        ),
        migrations.AlterField(
            model_name='reportitem',
            name='time_window',
            field=models.CharField(blank=True, choices=[('last_minute', 'Last Minute'), ('last_10_minutes', 'Last 10 Minutes'), ('last_hour', 'Last Hour'), ('last_day', 'Last Day'), ('last_week', 'Last Week'), ('last_year', 'Last Year')], max_length=20, null=True, verbose_name='Time window'),
        ),
    ]
