# Generated by Django 2.2.7 on 2020-02-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_auto_20200210_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportitem',
            name='type',
            field=models.TextField(blank=True, choices=[('data_table', 'Data Table'), ('bar_chart', 'Histogram'), ('series_chart', 'Series Chart'), ('line_chart', 'X/Y Scatter Plot'), ('summary', 'Summary')], null=True, verbose_name='Type'),
        ),
    ]
