# Generated by Django 2.2.7 on 2020-02-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_auto_20200211_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportitem',
            name='filter_type',
            field=models.CharField(blank=True, choices=[('filter_none', 'No Filter'), ('less_than', 'Less Than'), ('greater_than', 'Greater Than'), ('equal', 'Equal')], default='filter_none', max_length=20, null=True, verbose_name='Filter type'),
        ),
        migrations.AlterField(
            model_name='reportitem',
            name='type',
            field=models.TextField(blank=True, choices=[('data_table', 'Data Table'), ('histogram', 'Histogram'), ('series_chart', 'Time Series Chart'), ('scatter_plot', 'X/Y Scatter Plot'), ('summary', 'Summary')], null=True, verbose_name='Type'),
        ),
    ]
