# Generated by Django 2.2.7 on 2020-02-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0014_reportitem_plot_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportitem',
            name='plot_type',
            field=models.CharField(blank=True, choices=[('events_over_time', 'Count Of Events Over Time'), ('events_over_time_cumulative', 'Count Of Events Over Time (Cumulative)'), ('value_from_report', 'A Value From The Event')], max_length=30, null=True, verbose_name='Plot type'),
        ),
    ]
