# Generated by Django 2.2.7 on 2020-03-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0015_auto_20200218_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportitem',
            name='time_window',
            field=models.CharField(blank=True, choices=[('all_time', 'All Time'), ('last_minute', 'Last Minute'), ('last_10_minutes', 'Last 10 Minutes'), ('last_hour', 'Last Hour'), ('last_day', 'Last Day'), ('last_week', 'Last Week'), ('last_year', 'Last Year')], max_length=20, null=True, verbose_name='Time window'),
        ),
    ]
