# Generated by Django 2.2.7 on 2020-01-28 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0008_auto_20200117_0727'),
        ('timelines', '0002_timeline_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=200, null=True, verbose_name='key')),
                ('description', models.CharField(blank=True, max_length=400, null=True, verbose_name='Description')),
                ('ordering', models.IntegerField(default=1, verbose_name='Ordering steps')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streams.Stream')),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timelines.Timeline')),
            ],
            options={
                'verbose_name': 'TimelineItem',
                'verbose_name_plural': 'TimelineItems',
                'ordering': ('id',),
            },
        ),
    ]
