# Generated by Django 2.2.7 on 2020-01-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0003_timelineitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineitem',
            name='stream',
            field=models.CharField(max_length=200, verbose_name='stream'),
        ),
    ]
