# Generated by Django 2.2.7 on 2020-01-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0004_auto_20200128_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineitem',
            name='description_field',
            field=models.CharField(default='ghjhkk', max_length=400, verbose_name='Description fields'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timelineitem',
            name='title_field',
            field=models.CharField(default='jijijll', max_length=200, verbose_name='Title fields'),
            preserve_default=False,
        ),
    ]
