# Generated by Django 2.2.7 on 2020-02-14 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0008_auto_20200117_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'verbose_name': 'Schema',
                'verbose_name_plural': 'Schemas',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SchemaField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Field Name')),
                ('type_field', models.CharField(choices=[('string', 'String'), ('long', 'Long'), ('float', 'Float'), ('double', 'Double')], default='string', max_length=10, verbose_name='Type Field')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemas.Schema')),
            ],
            options={
                'verbose_name': 'SchemaField',
                'verbose_name_plural': 'SchemaFields',
                'ordering': ('id',),
            },
        ),
    ]
