# Generated by Django 2.2.7 on 2020-02-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemafield',
            name='type_field',
            field=models.CharField(choices=[('string', 'String'), ('int', 'Integer'), ('float', 'Float')], default='string', max_length=10, verbose_name='Type Field'),
        ),
    ]
