# Generated by Django 2.2.7 on 2020-05-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0004_auto_20200305_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemafield',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
