# Generated by Django 2.2.7 on 2020-05-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0005_schemafield_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='create_stream',
            field=models.BooleanField(default=True, verbose_name='Create Steam'),
        ),
    ]
