# Generated by Django 2.2.7 on 2020-05-11 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0006_schema_create_stream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schema',
            name='create_stream',
        ),
    ]
