# Generated by Django 2.2.7 on 2020-05-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0007_remove_schema_create_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemafield',
            name='type_field',
            field=models.CharField(choices=[('string', 'String'), ('long', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('date', 'Date')], default='string', max_length=10, verbose_name='Type Field'),
        ),
    ]
