# Generated by Django 2.2.7 on 2020-06-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0009_auto_20200521_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemafield',
            name='categorical',
            field=models.CharField(choices=[('categorical', 'Categorical'), ('continuous', 'Continuous')], default='categorical', max_length=30, verbose_name='Categorical'),
        ),
    ]
