# Generated by Django 2.2.7 on 2020-06-16 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0010_schemafield_categorical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemafield',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='schemas.Schema'),
        ),
    ]
