# Generated by Django 2.2.7 on 2020-06-25 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0011_auto_20200616_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemafield',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemas.Schema'),
        ),
    ]
