# Generated by Django 2.2.7 on 2019-11-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='ordering',
            field=models.IntegerField(default=1, verbose_name='Ordering steps'),
        ),
    ]
