# Generated by Django 2.2.7 on 2019-11-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0002_step_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='event',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Event description'),
        ),
        migrations.AlterField(
            model_name='step',
            name='topic',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Topic'),
        ),
    ]
