# Generated by Django 2.2.7 on 2020-01-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0004_simulation_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
