# Generated by Django 2.2.7 on 2020-01-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0005_auto_20200120_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
