# Generated by Django 2.2.7 on 2020-01-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0007_auto_20200127_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='run_count',
            field=models.IntegerField(default=1, verbose_name='Run Count'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='run_time',
            field=models.IntegerField(default=0, verbose_name='Run Time'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='run_type',
            field=models.CharField(choices=[('count', 'Run for a certain number of times'), ('time', 'Run for a period of time')], default='count', max_length=100, verbose_name='Run Type'),
        ),
    ]
