# Generated by Django 2.2.7 on 2020-01-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0008_auto_20200127_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='run_type',
            field=models.CharField(choices=[('once', 'Run Once'), ('count', 'Run Specified Number Of Times'), ('continuously', 'Run Continuously'), ('time', 'Run For Specified Time Period (In Minutes)')], default='once', max_length=100, verbose_name='Run Type'),
        ),
    ]
