# Generated by Django 2.2.7 on 2020-01-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0010_auto_20200128_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='is_regexp',
            field=models.BooleanField(default=False, verbose_name='Is Regexp?'),
        ),
    ]
