# Generated by Django 2.2.7 on 2020-01-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0011_step_is_regexp'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='replicas',
            field=models.PositiveIntegerField(default=1, verbose_name='Count Of Replicas'),
        ),
    ]
