# Generated by Django 2.2.7 on 2020-02-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0012_simulation_replicas'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='type_event',
            field=models.CharField(choices=[('static', 'Assign Static'), ('unique', 'Generate Unique')], default='static', max_length=6, verbose_name='Type Event'),
        ),
    ]
