# Generated by Django 2.2.7 on 2020-02-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0013_simulation_type_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='type_event',
            field=models.CharField(choices=[('unique', 'Generate Unique'), ('static', 'Assign Static')], default='unique', max_length=6, verbose_name='Type Event'),
        ),
    ]
