# Generated by Django 2.2.7 on 2020-02-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0014_auto_20200212_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='is_running',
            field=models.BooleanField(default=False, verbose_name='Running'),
        ),
    ]
