# Generated by Django 2.2.7 on 2020-04-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0016_simulation_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='completed',
            field=models.PositiveIntegerField(default=0, verbose_name='Counter of successful runs'),
        ),
    ]
