# Generated by Django 2.2.7 on 2020-05-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0017_auto_20200430_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='definition_type',
            field=models.CharField(choices=[('definition_json', 'JSON'), ('definition_schema', 'From Schema')], default='definition_json', max_length=20, verbose_name='Event definition type'),
        ),
    ]
