# Generated by Django 2.2.7 on 2020-06-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0019_auto_20200514_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='type_event',
            field=models.CharField(choices=[('unique', 'Generate Unique Messages On Each Run'), ('static', 'Replay The Same Messages On Each Run')], default='unique', max_length=6, verbose_name='Type Event'),
        ),
    ]
