# Generated by Django 2.2.7 on 2020-06-09 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0020_auto_20200608_1815'),
        ('simulations', '0020_auto_20200608_2037'),
    ]

    operations = [
    ]
