# Generated by Django 2.2.7 on 2020-02-04 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0002_kpi_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kpi',
            old_name='name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='kpi',
            old_name='description',
            new_name='metric',
        ),
    ]
