# Generated by Django 2.2.7 on 2020-07-05 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20200704_0836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='streamgroup',
            options={'ordering': ('id',), 'verbose_name': 'Stream Group', 'verbose_name_plural': 'Stream Groups'},
        ),
    ]
