# Generated by Django 2.2.7 on 2020-07-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0006_streamgroup_is_organisation_shared"),
    ]

    operations = [
        migrations.AlterField(
            model_name="streamgroup",
            name="is_organisation_shared",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
