# Generated by Django 2.2.7 on 2020-07-06 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0013_auto_20200619_0735"),
        ("groups", "0007_auto_20200705_2144"),
    ]

    operations = [
        migrations.AddField(
            model_name="streamgroup",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.Organisation",
            ),
        ),
    ]
