# Generated by Django 2.2.7 on 2020-06-05 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0002_auto_20200604_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaboration',
            name='is_active',
        ),
    ]
