# Generated by Django 2.2.7 on 2020-06-05 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20200117_1414'),
        ('collaboration', '0004_auto_20200605_0635'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collaboration',
            unique_together={('email', 'project')},
        ),
    ]
