# Generated by Django 2.2.7 on 2019-12-12 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stream',
            options={'ordering': ('id',), 'verbose_name': 'Stream', 'verbose_name_plural': 'Streams'},
        ),
        migrations.AddField(
            model_name='stream',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
