# Generated by Django 2.2.7 on 2019-12-16 11:08 test

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0002_auto_20191212_1240'),
    ]

    # operations = [
    #     # migrations.AlterField(
    #     #     model_name='stream',
    #     #     name='broker',
    #     #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Broker'),
    #     # ),
    # ]
