# Generated by Django 2.2.7 on 2019-12-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0004_stream_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='is_countable',
            field=models.BooleanField(default=False),
        ),
    ]
