# Generated by Django 2.2.7 on 2020-01-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0005_stream_is_countable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
