# Generated by Django 2.2.7 on 2020-01-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0006_auto_20200108_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='broker',
        ),
    ]
