# Generated by Django 2.2.7 on 2020-01-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0007_remove_stream_broker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='is_countable',
            field=models.BooleanField(default=False, verbose_name='Archive The Stream For Later Analysis'),
        ),
    ]
