# Generated by Django 2.2.7 on 2020-06-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0010_stream_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='retention_period',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
