# Generated by Django 2.2.7 on 2020-06-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0011_stream_retention_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='share',
            field=models.BooleanField(default=False, verbose_name='Share This Stream With Other Members Of My Organisation'),
        ),
    ]
