# Generated by Django 2.2.7 on 2020-07-03 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('streams', '0012_stream_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.StreamGroup'),
        ),
        migrations.AddField(
            model_name='stream',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
