# Generated by Django 2.2.7 on 2020-07-05 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0013_auto_20200703_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stream',
            options={'ordering': ('sort_order',), 'verbose_name': 'Stream', 'verbose_name_plural': 'Streams'},
        ),
    ]
