# Generated by Django 2.2.7 on 2020-03-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0003_schemafield_required'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='functionendpoint',
            options={'ordering': ('id',), 'verbose_name': 'FunctionEndpoint', 'verbose_name_plural': 'FunctionEndpoints'},
        ),
        migrations.AlterField(
            model_name='functionendpoint',
            name='type_field',
            field=models.CharField(choices=[('string', 'String'), ('int', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('date', 'Date')], default='string', max_length=10, verbose_name='Type Field'),
        ),
    ]
