# Generated by Django 2.2.7 on 2020-03-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0005_auto_20200305_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionendpoint',
            name='docker_image',
            field=models.CharField(default='here', max_length=120, verbose_name='Docker Image'),
            preserve_default=False,
        ),
    ]
