# Generated by Django 2.2.7 on 2020-06-07 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0010_schemafield_categorical'),
        ('functions', '0007_auto_20200305_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='functionendpoint',
            name='required',
        ),
        migrations.AddField(
            model_name='functionendpoint',
            name='inbound_schema',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='inbound_schema_set', to='schemas.Schema'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='functionendpoint',
            name='outbound_schema',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='outbound_schema_set', to='schemas.Schema'),
            preserve_default=False,
        ),
    ]
