# Generated by Django 2.2.7 on 2020-06-07 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0008_auto_20200607_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='functionendpoint',
            name='type_field',
        ),
    ]
